// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AjustarHoraFormatacao() {
  return window['go']['main']['App']['AjustarHoraFormatacao']();
}

export function AlterarDNS(arg1, arg2, arg3) {
  return window['go']['main']['App']['AlterarDNS'](arg1, arg2, arg3);
}

export function AlterarIP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AlterarIP'](arg1, arg2, arg3, arg4);
}

export function AlterarLayoutDeTeclado(arg1) {
  return window['go']['main']['App']['AlterarLayoutDeTeclado'](arg1);
}

export function AlterarNomeComputador(arg1) {
  return window['go']['main']['App']['AlterarNomeComputador'](arg1);
}

export function AtivarOffice(arg1) {
  return window['go']['main']['App']['AtivarOffice'](arg1);
}

export function AtivarWindows(arg1) {
  return window['go']['main']['App']['AtivarWindows'](arg1);
}

export function CorrigirCompartilhamentoWindows() {
  return window['go']['main']['App']['CorrigirCompartilhamentoWindows']();
}

export function ExecutarComando(arg1, arg2) {
  return window['go']['main']['App']['ExecutarComando'](arg1, arg2);
}

export function ExecutarComandoSimples(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecutarComandoSimples'](arg1, arg2, arg3);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function ObterInformacoesSistema() {
  return window['go']['main']['App']['ObterInformacoesSistema']();
}

export function ObterLayoutAtivo() {
  return window['go']['main']['App']['ObterLayoutAtivo']();
}

export function ObterLayoutsDisponiveis() {
  return window['go']['main']['App']['ObterLayoutsDisponiveis']();
}

export function ReiniciarComputador() {
  return window['go']['main']['App']['ReiniciarComputador']();
}

export function VerificarIPDisponivel(arg1) {
  return window['go']['main']['App']['VerificarIPDisponivel'](arg1);
}
