// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AtivarOffice(arg1) {
  return window['go']['main']['App']['AtivarOffice'](arg1);
}

export function AtivarWindows(arg1) {
  return window['go']['main']['App']['AtivarWindows'](arg1);
}

export function ExecutarComando(arg1, arg2) {
  return window['go']['main']['App']['ExecutarComando'](arg1, arg2);
}

export function ExecutarComandoSimples(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecutarComandoSimples'](arg1, arg2, arg3);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function ObterInformacoesSistema() {
  return window['go']['main']['App']['ObterInformacoesSistema']();
}
